### PR TITLE
fix deprecated parameter name

### PR DESCRIPTION
**Pull request by zunda-pixel**

### CODE REVIEW

**Review by stephencelis — APPROVED** [review]
Thanks! We'll probably hold off on merging this immediately since beta 5 is still relatively new, but maybe when beta 6 drops we can start updating these.

**Comment by zunda-pixel** [comment]
I confirmed Xcode 16.1 beta 1(16B5001e) can build this code.

@stephencelis 
Does `Package@swift-6.0.swift` need `swiftLanguageModes`?

**Comment by stephencelis** [comment]
@zunda-pixel The main issue is that `swiftLanguageModes` doesn't build in Xcode 16 beta 4 and below, so this would break for folks that haven't updated to the latest Xcode yet. So no harm in holding off on merging this PR for now, but we will merge it in the future.

**Review by stephencelis — APPROVED** [review]
Thanks! This should be good to go now!

**Pull request merged**
