### PR TITLE
Compile for Android

### PR DESCRIPTION
**Pull request by johankool**

### CODE REVIEW

**Comment by mbrandonw** [comment]
Hi @johankool, thanks for looking into this! Are you familiar with how we can get CI testing for android so that we can prevent problems like this in the future?

**Comment by johankool** [comment]
I used the Android SDK from here: https://github.com/finagolfin/swift-android-sdk then ran the .xctest on an actual device. The linked project has a workflow that shows how you can use the SDK and run tests on an emulator as they do that for amongst others the swift-argument-parser framework too.

**Comment by johankool** [comment]
BTW, quite amazing how little effort it takes to get the PointFree libraries to compile for Android. The below I have working already locally. PRs for those are depending on getting the fixes released for swift-issue-reporting/xctest-dynamic-overlay and swift-concurrency-extras.

- swift-case-paths
- swift-clocks
- swift-concurrency-extras
- swift-custom-dump
- swift-identified-collections
- swift-macro-testing
- swift-snapshot-testing

**Comment by johankool** [comment]
Now that this [PR](https://github.com/pointfreeco/swift-concurrency-extras/pull/48#event-15254167601) was merged by @stephencelis, it'd be great if this one could be merged too. That way I can prepare the PRs for the other projects as well to get them to work on Android.

**Review by stephencelis — APPROVED** [review]

**Comment by stephencelis** [comment]
Thanks!

**Pull request merged**
